LANGUAGES["zh"] = {
	Status: "状态",
	DashBoard: "首页",
	Show: "Show",
	Blocks: "Blocks",
	Conferences: "会议",
	About: "关于",
	Phone: "电话",
	Settings: "设置",
	Conferent: "会议室",
	Homes: "房间",
	Profiles: "Profiles",
	Help: "帮助",
	Play: "操作",
	State: "状态",
	Starttime: "开始时间",
	Endtime: "结束时间",
	Outcon: "未开始",
	Ingcon: "进行中",
	Endcon: "已结束",

	Overview: "概览",
	Calls: "Calls",
	Channels: "Channels",
	Users: "用户",
	Sofia: "Sofia",

	Call: "呼叫",
	DTMF: "拨号",

	Conference: "会议",
	Mute: "静音",
	unMute: "解除",
	Hangup: "挂机",
	Select: "选择",
	Lock: "锁定",
	unLock: "解锁",
	Loop: "循环",
	Speak: "发言",

	New: "新建",
	Delete: "删除",
	Edit: "修改",
	Save: "保存",
	Close: "关闭",
	Submit: "提交",

	"Create New Route": "新建路由",
	Routes: "路由",
	Route: "路由",
	Name: "名称",
	Description: "描述",
	Prefix: "前缀",
	Length: "长度",
	DNC: "被叫号码变换",
	SDNC: "主叫号码变换",
	Context: "呼叫源",
	Dest: "目的地",
	"Dest Type": "目的地类型",
	"Dest UUID": "目的地UUID",
	Body: "文本",
	"Confirm to Delete ?": "确认删除？",
	"Click me to toggle fast delete mode": "点击以切换快速删除模式",

	"Create New User": "新建用户",
	"CID Name": "主叫名称",
	"CID Number": "主叫号码",
	Number: "号码",
	Password: "密码",
	"VM Password": "VM密码",
	Domain: "域",
	Type: "类型",

	Email: "电子邮件",
	"Member ID": "成员ID",
	"CID": "主叫号码",

	Login: "登录",
	Logout: "退出",
	"Login with username and password": "输入用户名和密码登录",
	"Invalid username or password": "用户名/密码错误",

	"Mandatory fields left blank": "红色字段不能为空",
	"Saved at": "最后保存于 *{time}*",
	"Created At": "创建时间",

	"Create New Block": "创建新积木",
	"IVR Blocks": "IVR积木",
	"Blocks": "积木",
	"Block": "积木",
	Description: "描述",

	Gateways: "网关",
	Gateway: "网关",
	Realm: "服务器",
	Username: "用户名",
	Register: "注册",

	"Create New SIP Profile": "新建SIP Profile",

	Copyright: "版权所有 2016-2017 烟台小樱桃网络科技有限公司 保留所有权利",
	the_last_line_______: "Don't put anything beyond this line"
};
