LANGUAGES["zh"] = {

	"New Call": "新来电",
	"Answer Call": "接听",
	"Refuse Call": "拒接",
	"Select All": "全选",
	"Deselect All": "全不选",
	"Toggle Select": "反选",
	"Make Call": "呼叫",
	"Hangup Call": "挂断",

	Online: "在线",
	Offline: "离线",
	Idle: "空闲",
	Answered: "接听",
	Ringing: "振铃",

	Status: "状态",
	State: "状态",
	DashBoard: "首页",
	Show: "Show",
	Blocks: "Blocks",
	Conferences: "会议",
	Monitor: "监控",
	CDRs: "话单",
	CDR: "话单",
	About: "关于",
	"About XUI": "关于XUI",
	"XUI is a FreeSWITCH UI framework and implementation": "XUI是一个FreeSWITCH图形界面框架和实现",
	"More info": "详见",
	"Conference Profiles": "会议模板",
	"Conference Profile": "会议模板",
	Author: "作者",
	Version: "版本",
	Phone: "电话",
	"Socket Connected": "Socket已连接",
	Settings: "设置",
	Profiles: "Profiles",
	Help: "帮助",
	Search: "查询",
	Last: "最近",
	Refresh: "刷新",
	Add: "添加",
	"Click to Change": "点击修改...",
	"Internal Error": "内部错误: {msg}",

	Overview: "状态",
	Calls: "呼叫",
	Callgroup: "呼叫组",
	Channels: "通道",
	Users: "用户",
	Groups: "分组",
	Sofia: "Sofia",

	Call: "呼叫",
	DTMF: "拨号",
	Hangup: "挂断",
	Transfer: "转接",
	Answer: "接听",
	Reject: "拒接",
	Audio: "音频",
	Video: "视频",
	Idle: "空闲",
	Trying: "呼叫...",
	Ringing: "振铃...",
	Active: "通话中",
	Busy: "通话中",
	Held: "保持",

	"Call State": "呼叫状态",
	Direction: "方向",
	Created: "创建时间",

	Registrations: "注册",
	"Reg User": "注册用户",
	Expires: "过期时间",
	"Network IP": "网络地址",
	"Network Port": "端口",
	"Network Proto": "协议",
	Hostname: "主机名",
	Metadata: "元数据",
	Group: "组",
	"Parent Group": "所属组",
	"Add Member(s)": "添加用户",
	"Remove All Member(s)": "移除所有用户",
	"Group Members": "组成员",
	Contact: "联系地址",
	Reg: "注册",
	Unreg: "注销",
	FileName: "文件名",
	"Token / Url": "令牌/网址",
	URL: "网址",

	Alias: "别名",
	Command: "命令",
	HostName: "主机名",
	Sticky: "粘性",

	Task: "任务",
	"Task Desc": "任务描述",
	"Task Group": "任务组",
	"Task SQL Manager": "SQL管理器",

	Conference: "会议",
	"Conference Name": "会议名称",
	Mute: "静音",
	unMute: "解除",
	Hangup: "挂机",
	Select: "选择",
	Lock: "锁定",
	unLock: "解锁",
	Loop: "循环",
	Speak: "发言",
	Capacity: "容量",
	PIN: "密码",
	Moderator: "管理员",
	Total: "总数",

	"Conference Rooms": "会议室",
	"Create New Room": "创建新会议室",
	"Add New Member": "添加与会者",
	"Add Member": "添加与会者",
	"Members": "与会者",

	"Display as Table": "以表格形式显示",
	"Display as List": "以列表形式显示",
	"Toggle Toolbar Text": "切换按钮图标文字提示",

	"Create New Conference Profile": "创建新会议模板",

	New: "新建",
	Edit: "编辑",
	Delete: "删除",
	"Export XML": "导出 XML",
	"Export SVG": "导出 SVG",
	"Export Lua": "导出 Lua",
	Save: "保存",
	Close: "关闭",
	Submit: "提交",

	"Create New Route": "新建路由",
	"Show SysRoute": "显示系统路由",
	"Hide SysRoute": "隐藏系统路由",
	Routes: "路由",
	Route: "路由",
	Name: "名称",
	Description: "描述",
	Prefix: "起始号码",
	Length: "长度",
	DNC: "被叫号码变换",
	SDNC: "主叫号码变换",
	Context: "呼叫源",
	Dest: "目的地",
	"Dest Type": "目的地类型",
	"Dest UUID": "目的地UUID",
	Body: "文本",
	"Confirm to Delete ?": "确认删除？",
	"Click me to toggle fast delete mode": "点击以切换快速删除模式",
	"Local User": "本地用户",
	System: "系统",
	"IVR Block": "IVR积木",
	"Detail": "详细",

	FS_DEST_USER: "本地用户",
	FS_DEST_GATEWAY: "网关",
	FS_DEST_USERGW: "用户网关",
	FS_DEST_SYSTEM: "系统",
	FS_DEST_IP: "IP地址",
	FS_DEST_IVRBLOCK: "积木",
	FS_DEST_CONFERENCE: "会议",

	"Create New User": "新建用户",
	Import: "导入",
	"CID Name": "主叫名称",
	"CID Number": "主叫号码",
	Number: "号码",
	Password: "密码",
	"VM Password": "VM密码",
	Domain: "域",
	Type: "类型",
	Syntax: "语法",
	Data: "数据地址",

	Email: "电子邮件",
	"Member ID": "成员ID",
	"CID": "主叫号码",

	Login: "登录",
	Logout: "退出",
	"User settings": "用户设置",
	"Login with username and password": "输入用户名和密码登录",
	"Invalid username or password": "用户名/密码错误",

	"Mandatory fields left blank": "红色字段不能为空",
	"Saved at": "最后保存于 *{time}*",
	"Created At": "创建时间",
	HTTPERR: "[{code}] {statusText}",

	"Create New Block": "创建新积木",
	"IVR Blocks": "IVR积木",
	"IVR Block": "IVR积木",
	"Blocks": "积木",
	"Block": "积木",

	Time: "时间",
	Logic: "逻辑",
	Loops: "循环",
	Math: "数学",
	Text: "文本",
	Lists: "列表",
	Color: "颜色",
	Variables: "变量",
	Functions: "函数",

	Gateways: "网关",
	Gateway: "网关",
	Server: "服务器",
	Username: "用户名",
	Register: "注册",
	Reg: "注册",
	Unreg: "注销",

	Realm: "域",
	Key: "键",
	Value: "值",
	Description: "描述",
	Order: "排序",
	Tickets: "工单",

	SYSTEM: "系统",
	LOCAL: "本地用户",
	IVRBLOCK: "IVR积木",
	GATEWAY: "网关",


	"Create New SIP Profile": "新建SIP Profile",
	Stop: "停止",
	Restart: "重启",
	Rescan: "重新扫描",
	Params: "参数",
	More: "更多",

	"Media Files": "媒体文件",
	"Drag and drop files here to upload": "将文件拖到此处上传",
	"Create New Dict": "新建字典",
	"Dicts": "数据字典",
	"Create New Gateway": "新建网关",
	Control: "控制",
	Template: "模板",
	Upload: "上传",
	Modules: "模块",
	Record: "录音",
	"Two different ways to record": "请选用一种方式录音",
	"Use any phone, Call *991234 to record after BEEP": "用电话呼叫 *991234，『嘀』声后开始录音",
	"Callback to record after BEEP": "呼叫一个号码，在『嘀』声后开始录音",
	"Recording to": "正在录音 *{path}*",
	"Record completed": "录音完成 *{path}*",

	"Dest Number": "被叫号码",
	Start: "开始",
	End: "结束",
	Duration: "总时长",
	"Bill Sec": "计费时长",
	Cause: "挂机原因",
	"Account Code": "计费号码",
	"Import New Users": "导入新用户",
	"FIFO CDR": "队列话单",
	"FIFO CDRs": "队列话单",
	"Bridged Number": "服务号码",
	"FIFO Name": "队列",
	FIFO: "队列",
	"days": "{day}天",
	"Total Rows": "总行数",
	"Last Page": "尾页",
	"First Page": "首页",
	"Next Page": "下一页",
	"Prev Page": "上一页",
	"Current Page/Total Page": "当前页/总页数",
	"Create New FIFO": "创建新的队列",
	"Add FIFO Member": "创建新的队列成员",
	"Edit FIFO": "编辑队列",
	"FIFO Member": "队列成员",
	"FIFO Member Info": "队列成员信息",
	"Importance": "重要等级",
	"Dial String": "拨号串",
	"Timeout": "超时",
	"Simo": "并发",
	"Lag": "延迟",
	"Extn": "分机号",
	"Reparse": "重载队列设置",
	"Auto Record": "自动录音",
	"OB Per Cycle": "同时外呼数",
	"OB Per Cycle Min": "最小同时外呼数",
	"OB Name": "外呼名称",
	"OB Strategy": "外呼策略",
	"OB Priority": "外呼优先级",
	"Retry Delay": "重拨延时",
	"Record Template": "录音模板",
	"FIFO Reparsed": "队列设置重载成功",
	"FIFO Info": "队列信息",

	Greet_long: "欢迎音",
	Greet_short: "提示音",
	Invalid_sound: "错键提示音",
	Exit_sound: "挂断音",
	Transfer_sound: "转接音",
	Max_failures: "最大失败次数",
	Max_timeouts: "最大超时次数",
	Exec_on_max_failures: "执行最大失败数",
	Exec_on_max_timeouts: "执行最大超时数",
	Confirm_macro: "确认语音宏",
	Confirm_key: "确认键",
	Tts_engine: "TTS引擎",
	Tts_voice: "TTS嗓音",
	Confirm_attempts: "尝试次数",
	Digit_len: "最大收号数",
	Inter_digit_timeout: "两次按键最大间隔",
	Digits: "按键数",
	Action: "执行",
	Args: "参数",
	"Add IVR ACTION": "添加IVR执行菜单",
	"Create New IVR":"创建新的IVR",


	"Multicasts": "组播",
	"Source": "源",
	"Codec Name": "编码",
	"Codec Ms": "打包时间间隔",
	"Multicast Address": "组播地址",
	"Multicast Port": "组播端口",
	"Sample Rate": "采样频率",
	"Create New mcast": "新建组播",

	"Terminal": "终端",

	"System Settings": "系统设置",
	"Baidu TTS": "百度TTS",
	"EventSocket Settings": "EventSocket设置",
	Fetch: "获取",
	"Video Settings": "视频设置",
	"Best frame rate": "最佳帧率",
	"Resolution": "分辨率",
	Camera: "摄像头",
	"Automatically determine speed and resolution settings": "根据网速自动选择最佳分辨率",
	"Recheck bandwidth before each outgoing call": "在恢复上一次通话前询问",
	"Scale Remote Video To Match Camera Resolution": "自动缩放远端视频到本地摄像头分辨率",
	"Ask before recovering call": "在恢复上一次通话前询问",
	"Preview Settings": "预览设置",
	"Auto Gain Control": "自动增益控制",
	"Refresh Device List": "刷新设备列表",
	"Factory Reset": "恢复默认设置",
	"Share device": "共享设备",
	"No Camera": "无",
	"Audio Settings": "音频设置",
	"Echo Cancellation": "回声消除",
	"Noise Suppression": "噪音抑制",
	"Highpass Filter": "高通滤波",
	"Speaker": "喇叭",
	"Microphone": "麦克风",
	"Stereo Audio": "立体声",
	"Use STUN": "启用STUN",
	"Check Network Speed": "测试网络速度",
	"General Settings": "通话设置",
	"Firmware settings": "固件设置",
	"Built-in output": "内建输出",
	"Log": "日志",
	"Sound Files": "声音文件",

	Enabled: "启用",
	Disabled: "禁用",
	Load: "加载",
	Unload: "卸载",
	Reload: "重载",
	Yes: "是",
	No: "否",
	"Module reloaded": "模块重新加载成功",

	"Download Log": "下载日志",


	"eventsocket-listen-ip": "监听IP，可以是127.0.0.1，0.0.0.0，或一个真实的IP地址如192.168.0.1，支持IPV6",
	"eventsocket-debug": "开启调试模式",
	"eventsocket-nat-map": "nat-map",
	"eventsocket-listen-port": "监听端口",
	"eventsocket-password": "密码",
	"eventsocket-apply-inbound-acl": "启动ACL",
	"eventsocket-stop-on-bind-error": "如果无法绑定监听端口，则不加载该模块",
	abs_path: "路径",
	ext: "扩展名",
	dir_path: "所在文件夹",
	file_size: "大小",
	mime: "文件类型",
	original_file_name: "原始文件名",
	created_epoch: "创建时间",
	updated_epoch: "更新时间",
	channel_uuid: "路径识别码",
	FileShow: "文件预览",
	HiddenFileShow: "关闭预览",
	yes: "是",
	no: "否",
	Missed: "未接",
	"Hidden Record": "隐藏录音",
	ACLs: "访问控制列表",
	ACL: "访问控制列表",
	Default: "默认",
	node: "节点",
	Cidr: "无类域间路由",

	Subject: "主题",
	TICKET_ST_NEW: "未处理",
	TICKET_ST_PROCESSING: "处理中",
	TICKET_ST_DONE: "已完成",
	"Create New Ticket": "新建工单",
	Content: "内容",

	Headimgurl: "头像",
	Nickname: "昵称",
	Sex: "性别",
	Province: "省份",
	City: "城市",
	Country: "国家",
	Language: "语言",
	Privilege: "权限",
	App_type: "终端",
	Male: "男",
	Female: "女",
	Unknown: "未知",
	"Wechat User": "微信用户",
	"Wechat Users": "微信用户",

	Copyright: "版权所有 2016-" + new Date().getFullYear() + " 烟台小樱桃网络科技有限公司 保留所有权利",
	the_last_line_______: "Don't put anything beyond this line"
};
