LANGUAGES["zh"] = {
	Status: "状态",
	DashBoard: "首页",
	Show: "Show",
	Blocks: "Blocks",
	Conferences: "会议",
	About: "关于",
	Phone: "电话",
	Settings: "设置",
	Profiles: "Profiles",
	Help: "帮助",

	Overview: "概览",
	Calls: "Calls",
	Channels: "Channels",
	Users: "用户",
	Sofia: "Sofia",

	Call: "呼叫",

	Conference: "会议",
	Mute: "静音",
	unMute: "解除",
	Hangup: "挂机",
	Select: "选择",
	Lock: "锁定",
	unLock: "解锁",
	Loop: "循环",
	Speak: "发言",

	New: "新建",
	Delete: "删除",
	Save: "保存",
	Submit: "提交",

	"Create New Route": "新建路由",
	Routes: "路由",
	Route: "路由",
	Name: "名称",
	Description: "描述",
	Prefix: "前缀",
	Length: "长度",
	DNC: "被叫号码变换",
	SDNC: "主叫号码变换",
	Context: "呼叫源",
	Dest: "目的地类型",
	"Dest Type": "目的地类型",
	"Dest UUID": "目的地UUID",
	Body: "文本",
	"Confirm to Delete ?": "确认删除？",
	"Click me to toggle fast delete mode": "点击以切换快速删除模式",

	"Create New User": "新建路由",
	"CID Name": "主叫名称",
	"CID Number": "主叫号码",
	Number: "号码",
	Password: "密码",
	"VM Password": "VM密码",
	Domain: "域",
	Type: "类型",

	Email: "电子邮件",
	"Member ID": "成员ID",
	"CID": "主叫号码",

	Login: "登录",
	Logout: "退出",
	"Login with username and password": "输入用户名和密码登录",

	the_last_line_______: "Don't put anything beyond this line"
};
